fasta:
    none
workdir:
    none
long_reads:
    none
short_reads_1:
    none
short_reads_2:
    none
batch_file:
  none
max_threads:
    8
virsorter_data:
    /srv/db/virsorter2
vibrant_data:
    /srv/db/vibrant/1.2.1
gtdbtk_folder:
    /srv/db/gtdbtk/official/release89
busco_folder:
    /srv/longreads/nanopore/busco